name: build

on:
  push:
    branches:
    - hugo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checking out...'
      uses: actions/checkout@v2

    - name: 'Building...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: ZenLian/ZenLian.github.io
        DEPLOY_BRANCH: gh-pages
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: Asia/Shanghai